[package]
name = "installed_apps_client"
version = "0.1.0"
edition = "2021"

[dependencies]
winreg = "0.10"
reqwest = { version = "*", features = ["blocking"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"